name: print-hello

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  print-hello-python:
    name: Print Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install deps
      run: pip3 install --user requests beautifulsoup4 pandas
    - run: python football.py
    - name: Commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          mv TextFootball.json TextFootball.json
          git add TextFootball.json
          git commit -m "update json"|| echo "Nothing to update"
          git push

  print-hello-r:
    name: Print R
    runs-on: ubuntu-latest
    needs: print-hello-python
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - run: Rscript -e 'print("hello")'



